version: '3'
services:
#mssql docker
  rs2farmcommerce-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1402:1433
    expose:
      - 1433
    networks:
      - farmcommercenet2024

  rs2farmcommerce-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=rs2farmcommerce-sql,1433;Database=RS2FarmCommerce;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7278:7278
    networks:
      - farmcommercenet2024
    links:
      - rs2farmcommerce-sql
    depends_on:
      - rs2farmcommerce-sql
      
networks:
  farmcommercenet2024:
    driver: bridge      